// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import DropzoneController from "./dropzone_controller"
application.register("dropzone", DropzoneController)

import SectionsController from "./sections_controller"
application.register("sections", SectionsController)

import ShowLimitController from "./show_limit_controller"
application.register("show-limit", ShowLimitController)

import ModalController from "./modal_controller"
application.register("modal", ModalController)

import PaymentController from "./payment_controller"
application.register("payment", PaymentController)

import { Multiselect } from '@wizardhealth/stimulus-multiselect'
application.register('multiselect', Multiselect)
